/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.DocGiaCtrl;
import controller.MuonTraCtrl;
import controller.SachCtrl;
import controller.mainFormPanelWellcomCtrl;
import controller.panelNVCtr;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.DocGia;
import model.NhanVien;

/**
 *
 * @author coc
 */
public class MainForm extends javax.swing.JFrame {

    private NhanVien nv;

    /**
     * Creates new form MainForm
     */
    public void setNv(NhanVien nv) {
        this.nv = nv;
    }

    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RoSachDialog = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        RSDMaSach = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        RSDTenSach = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        RSDDongia = new javax.swing.JTextField();
        RSDSpinSoLuongSach = new javax.swing.JSpinner();
        RSDspinSoNgayMuon = new javax.swing.JSpinner();
        RSDLuu = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        RSDTongTien = new javax.swing.JLabel();
        jTabbedPane1 = new raven.tabbed.TabbedPaneCustom();
        panelChaoMung = new javax.swing.JPanel();
        panelNV = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbTenNV = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbVaiTro = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbSachDaChoMuon = new javax.swing.JLabel();
        cmbChucNang = new javax.swing.JComboBox<>();
        btSave = new javax.swing.JButton();
        pfpass = new javax.swing.JPasswordField();
        btLogout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbTopSach = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbTopNV = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TbTopKH = new javax.swing.JTable();
        jpannelMuonTra = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbResultTb1 = new javax.swing.JTable();
        panelltimkiem1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tftenS1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btSearch1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfGiaLN1 = new javax.swing.JTextField();
        tftacGia1 = new javax.swing.JTextField();
        tfnhaXB1 = new javax.swing.JTextField();
        tfnamXB1 = new javax.swing.JTextField();
        tfMaDS1 = new javax.swing.JTextField();
        tfGiaNN1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cmbSapXep1 = new javax.swing.JComboBox<>();
        panelRoSach = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbRoSach = new javax.swing.JTable();
        btDelete1 = new javax.swing.JButton();
        panelDocGia = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        tfSoDTDocGia = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tfTenDocGia = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btXacNhan = new javax.swing.JButton();
        cmbLoadSoDTDocGia = new javax.swing.JComboBox<>();
        tfKhoaDocGia = new javax.swing.JTextField();
        tfLopDocGia = new javax.swing.JTextField();
        JPannelQuanLiSach = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        tfTenS2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tfTacGia2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tfNhaXB2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tfNamXB2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tfGiaNN2 = new javax.swing.JTextField();
        tfGiaLN2 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        tfMaDS2 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        cmbSapXep2 = new javax.swing.JComboBox<>();
        btSearch2 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        btAdd2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbResultSach2 = new javax.swing.JTable();
        btfix2 = new javax.swing.JButton();
        btdelete2 = new javax.swing.JButton();

        RoSachDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        RoSachDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                RoSachDialogWindowOpened(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Đơn Giá");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Số Lượng Sách Mượn");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Ngày Mượn Sách");

        RSDSpinSoLuongSach.setModel(new javax.swing.SpinnerNumberModel(1.0f, 1.0f, null, 1.0f));
        RSDSpinSoLuongSach.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RSDSpinSoLuongSachStateChanged(evt);
            }
        });

        RSDspinSoNgayMuon.setModel(new javax.swing.SpinnerNumberModel(1.0f, 1.0f, null, 1.0f));
        RSDspinSoNgayMuon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RSDspinSoNgayMuonStateChanged(evt);
            }
        });

        RSDLuu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RSDLuu.setText("Lưu");
        RSDLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RSDLuuActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Mã Sách");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel28.setText("Tổng Số Tiền :");

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel29.setText("Tên Sách");

        RSDTongTien.setText("jLabel7");

        javax.swing.GroupLayout RoSachDialogLayout = new javax.swing.GroupLayout(RoSachDialog.getContentPane());
        RoSachDialog.getContentPane().setLayout(RoSachDialogLayout);
        RoSachDialogLayout.setHorizontalGroup(
            RoSachDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoSachDialogLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(RoSachDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel29)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RoSachDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RSDMaSach)
                    .addComponent(RSDTenSach, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(RSDDongia, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RoSachDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(RoSachDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RSDLuu)
                    .addComponent(RSDSpinSoLuongSach)
                    .addComponent(RSDspinSoNgayMuon, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(RSDTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        RoSachDialogLayout.setVerticalGroup(
            RoSachDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoSachDialogLayout.createSequentialGroup()
                .addGroup(RoSachDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RoSachDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(RSDMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RoSachDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(RoSachDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(RSDSpinSoLuongSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RoSachDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(RSDTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(RSDspinSoNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RoSachDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(RSDDongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(RoSachDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(RSDTongTien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(RSDLuu)
                .addGap(20, 20, 20))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        panelChaoMung.setBackground(new java.awt.Color(153, 204, 255));

        panelNV.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Hi,");

        lbTenNV.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbTenNV.setText("TenNV");
        lbTenNV.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Vai trò:");

        lbVaiTro.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbVaiTro.setText("chucvu");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Số sách đã cho mượn:");

        lbSachDaChoMuon.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbSachDaChoMuon.setText("jLabel4");

        cmbChucNang.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmbChucNang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cài đặt", "Đổi tên", "Đổi Mật Khẩu" }));
        cmbChucNang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbChucNangActionPerformed(evt);
            }
        });

        btSave.setBackground(new java.awt.Color(0, 102, 102));
        btSave.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btSave.setForeground(new java.awt.Color(255, 255, 255));
        btSave.setText("Save");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        btLogout.setBackground(new java.awt.Color(0, 102, 102));
        btLogout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btLogout.setForeground(new java.awt.Color(255, 255, 255));
        btLogout.setText("Logout");
        btLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNVLayout = new javax.swing.GroupLayout(panelNV);
        panelNV.setLayout(panelNVLayout);
        panelNVLayout.setHorizontalGroup(
            panelNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNVLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTenNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelNVLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lbVaiTro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pfpass)
                    .addGroup(panelNVLayout.createSequentialGroup()
                        .addGroup(panelNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelNVLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(lbSachDaChoMuon))
                            .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNVLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelNVLayout.setVerticalGroup(
            panelNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbTenNV))
                .addGap(18, 18, 18)
                .addGroup(panelNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbVaiTro))
                .addGap(18, 18, 18)
                .addGroup(panelNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbSachDaChoMuon))
                .addGap(18, 18, 18)
                .addComponent(cmbChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pfpass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TOP sách", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N

        tbTopSach.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tbTopSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tbTopSach);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TOP nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N

        tbTopNV.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tbTopNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tbTopNV);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TOP khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N

        TbTopKH.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TbTopKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(TbTopKH);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );

        javax.swing.GroupLayout panelChaoMungLayout = new javax.swing.GroupLayout(panelChaoMung);
        panelChaoMung.setLayout(panelChaoMungLayout);
        panelChaoMungLayout.setHorizontalGroup(
            panelChaoMungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelChaoMungLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelChaoMungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelChaoMungLayout.createSequentialGroup()
                        .addGroup(panelChaoMungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(4, 4, 4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelChaoMungLayout.setVerticalGroup(
            panelChaoMungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelChaoMungLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelChaoMungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelChaoMungLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(130, 130, 130))
        );

        jTabbedPane1.addTab("Chào mừng", null, panelChaoMung, "");
        panelChaoMung.getAccessibleContext().setAccessibleName("");

        jpannelMuonTra.setBackground(new java.awt.Color(204, 204, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách sách", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14))); // NOI18N

        tbResultTb1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tbResultTb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sách", "Tên Sách", "Tác Giả", "Nhà Xuất Bản", "Năm Xuất Bản", "Đơn Giá"
            }
        ));
        tbResultTb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbResultTb1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbResultTb1);
        if (tbResultTb1.getColumnModel().getColumnCount() > 0) {
            tbResultTb1.getColumnModel().getColumn(3).setHeaderValue("Nhà Xuất Bản");
            tbResultTb1.getColumnModel().getColumn(4).setHeaderValue("Năm Xuất Bản");
            tbResultTb1.getColumnModel().getColumn(5).setHeaderValue("Đơn Giá");
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        panelltimkiem1.setBackground(new java.awt.Color(255, 255, 255));
        panelltimkiem1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Tác Giả");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Nhà Xuất Bản");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Năm Xuất Bản");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Tên Sách");

        btSearch1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btSearch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        btSearch1.setText("Search");
        btSearch1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btSearch1ItemStateChanged(evt);
            }
        });
        btSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearch1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Mã đầu sách");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("Đơn giá");

        tfGiaLN1.setText("99999999999999999");

        tfGiaNN1.setText("0");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Sắp xếp theo");

        cmbSapXep1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbSapXep1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ASC", "DESC" }));

        javax.swing.GroupLayout panelltimkiem1Layout = new javax.swing.GroupLayout(panelltimkiem1);
        panelltimkiem1.setLayout(panelltimkiem1Layout);
        panelltimkiem1Layout.setHorizontalGroup(
            panelltimkiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelltimkiem1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelltimkiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelltimkiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelltimkiem1Layout.createSequentialGroup()
                        .addComponent(cmbSapXep1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSearch1))
                    .addComponent(tftenS1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelltimkiem1Layout.createSequentialGroup()
                        .addGroup(panelltimkiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tftacGia1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfGiaNN1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelltimkiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelltimkiem1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfnhaXB1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfnamXB1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                            .addGroup(panelltimkiem1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tfGiaLN1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfMaDS1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        panelltimkiem1Layout.setVerticalGroup(
            panelltimkiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelltimkiem1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelltimkiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tftenS1))
                .addGap(18, 18, 18)
                .addGroup(panelltimkiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(tftacGia1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(tfnamXB1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfnhaXB1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelltimkiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tfGiaLN1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(tfMaDS1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGiaNN1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelltimkiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cmbSapXep1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSearch1))
                .addGap(20, 20, 20))
        );

        panelRoSach.setBackground(new java.awt.Color(255, 255, 255));
        panelRoSach.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rổ sách", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14))); // NOI18N

        tbRoSach.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        tbRoSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sách", "Tên Sách", "Đơn Giá", "Số lượng sách", "Số ngày mượn"
            }
        ));
        jScrollPane1.setViewportView(tbRoSach);

        btDelete1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btDelete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        btDelete1.setText("Xóa");
        btDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelete1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRoSachLayout = new javax.swing.GroupLayout(panelRoSach);
        panelRoSach.setLayout(panelRoSachLayout);
        panelRoSachLayout.setHorizontalGroup(
            panelRoSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoSachLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRoSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(panelRoSachLayout.createSequentialGroup()
                        .addComponent(btDelete1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelRoSachLayout.setVerticalGroup(
            panelRoSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btDelete1)
                .addContainerGap())
        );

        panelDocGia.setBackground(new java.awt.Color(255, 255, 255));
        panelDocGia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin đọc giả", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Số điện thoại");

        tfSoDTDocGia.setToolTipText("har");
        tfSoDTDocGia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfSoDTDocGiaFocusLost(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel18.setText("Tên đọc giả");
        jLabel18.setToolTipText("");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel19.setText("Lớp");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel20.setText("Khoa");

        btXacNhan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btXacNhan.setText("Xác nhận");
        btXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXacNhanActionPerformed(evt);
            }
        });

        cmbLoadSoDTDocGia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbLoadSoDTDocGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbLoadSoDTDocGiaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelDocGiaLayout = new javax.swing.GroupLayout(panelDocGia);
        panelDocGia.setLayout(panelDocGiaLayout);
        panelDocGiaLayout.setHorizontalGroup(
            panelDocGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDocGiaLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panelDocGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addGroup(panelDocGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDocGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfTenDocGia)
                    .addComponent(tfSoDTDocGia)
                    .addGroup(panelDocGiaLayout.createSequentialGroup()
                        .addComponent(btXacNhan)
                        .addGap(0, 204, Short.MAX_VALUE))
                    .addComponent(cmbLoadSoDTDocGia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfKhoaDocGia, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfLopDocGia, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        panelDocGiaLayout.setVerticalGroup(
            panelDocGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDocGiaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDocGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSoDTDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbLoadSoDTDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(panelDocGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfTenDocGia)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDocGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLopDocGia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDocGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfKhoaDocGia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpannelMuonTraLayout = new javax.swing.GroupLayout(jpannelMuonTra);
        jpannelMuonTra.setLayout(jpannelMuonTraLayout);
        jpannelMuonTraLayout.setHorizontalGroup(
            jpannelMuonTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpannelMuonTraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpannelMuonTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelltimkiem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpannelMuonTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpannelMuonTraLayout.createSequentialGroup()
                        .addComponent(panelDocGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(panelRoSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jpannelMuonTraLayout.setVerticalGroup(
            jpannelMuonTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpannelMuonTraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpannelMuonTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpannelMuonTraLayout.createSequentialGroup()
                        .addComponent(panelRoSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpannelMuonTraLayout.createSequentialGroup()
                        .addComponent(panelltimkiem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mượn Trả", jpannelMuonTra);

        JPannelQuanLiSach.setBackground(new java.awt.Color(204, 204, 255));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14))); // NOI18N

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setText("Tên Sách");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setText("Tác Giả");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setText("Nhà Xuất Bản");

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel24.setText("Năm Xuất Bản");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel25.setText("Đơn giá");

        tfGiaNN2.setText("0");

        tfGiaLN2.setText("9999999999999999999999");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel26.setText("Mã đầu sách");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel27.setText("Sắp xếp theo");

        cmbSapXep2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbSapXep2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ASC", "DESC" }));

        btSearch2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btSearch2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        btSearch2.setText("Search");
        btSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearch2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btSearch2))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel12Layout.createSequentialGroup()
                                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel12Layout.createSequentialGroup()
                                                .addComponent(tfTacGia2, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(22, 22, 22)
                                                .addComponent(jLabel26)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(tfMaDS2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel12Layout.createSequentialGroup()
                                                .addComponent(tfTenS2, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(22, 22, 22)
                                                .addComponent(jLabel23)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tfNhaXB2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfNamXB2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel12Layout.createSequentialGroup()
                                        .addGap(468, 468, 468)
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfGiaNN2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(tfGiaLN2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 108, Short.MAX_VALUE))))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbSapXep2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNhaXB2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(jLabel24)
                        .addComponent(tfNamXB2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(tfTenS2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tfTacGia2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(tfMaDS2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25)
                        .addComponent(tfGiaLN2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfGiaNN2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel27)
                        .addComponent(cmbSapXep2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(btSearch2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14))); // NOI18N

        btAdd2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btAdd2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        btAdd2.setText("Thêm");

        tbResultSach2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tbResultSach2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tbResultSach2);

        btfix2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btfix2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit.png"))); // NOI18N
        btfix2.setText("Sửa");

        btdelete2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btdelete2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        btdelete2.setText("Xóa");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btAdd2)
                .addGap(18, 18, 18)
                .addComponent(btfix2)
                .addGap(18, 18, 18)
                .addComponent(btdelete2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdd2)
                    .addComponent(btfix2)
                    .addComponent(btdelete2))
                .addContainerGap())
        );

        javax.swing.GroupLayout JPannelQuanLiSachLayout = new javax.swing.GroupLayout(JPannelQuanLiSach);
        JPannelQuanLiSach.setLayout(JPannelQuanLiSachLayout);
        JPannelQuanLiSachLayout.setHorizontalGroup(
            JPannelQuanLiSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPannelQuanLiSachLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPannelQuanLiSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        JPannelQuanLiSachLayout.setVerticalGroup(
            JPannelQuanLiSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPannelQuanLiSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quản lí sách", JPannelQuanLiSach);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        // TODO add your handling code here:
        char[] c = this.pfpass.getPassword();

        try {
            this.nv = panelNVCtr.save(cmbChucNang, nv, new String(c));
            loadPanelNV();
            panelNVCtr.show(pfpass, btSave, false);
            this.cmbChucNang.setSelectedIndex(0);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(panelChaoMung, ex);
        }

    }//GEN-LAST:event_btSaveActionPerformed

    private void cmbChucNangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbChucNangActionPerformed
        // TODO add your handling code here:
        panelNVCtr.CaiDat(cmbChucNang, pfpass, btSave);
    }//GEN-LAST:event_cmbChucNangActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

        //load panel NhanVien
        loadPanelNV();
        panelNVCtr.show(pfpass, btSave, false);
        this.cmbChucNang.setSelectedIndex(0);
        ///load cac panel top
        mainFormPanelWellcomCtrl.loadTableTop(tbTopSach, mainFormPanelWellcomCtrl.tbTopSach);
        mainFormPanelWellcomCtrl.loadTableTop(TbTopKH, mainFormPanelWellcomCtrl.tbTopDG);
        mainFormPanelWellcomCtrl.loadTableTop(tbTopNV, mainFormPanelWellcomCtrl.tbTopNV);


    }//GEN-LAST:event_formWindowOpened

    private void btLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoutActionPerformed
        // TODO add your handling code here:
        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btLogoutActionPerformed

    private void btSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearch1ActionPerformed
        // TODO add your handling code here:
        SachCtrl sachCtrl = new SachCtrl();
        String mads, tenS, tacGia, nhaXB, namXB, sortOrderby;
        float dongiaNN, dongiaLL;
        mads = getStr(tfMaDS1);
        tenS = getStr(tftenS1);
        tacGia = getStr(tftacGia1);
        nhaXB = getStr(tfnhaXB1);
        namXB = getStr(tfnamXB1);
        sortOrderby = getStr(cmbSapXep1);
        dongiaNN = Float.parseFloat(tfGiaNN1.getText().trim());
        dongiaLL = Float.parseFloat(tfGiaLN1.getText().trim());
        sachCtrl.SachtoTable(tbResultTb1, mads, tenS, tacGia, nhaXB, namXB, dongiaNN, dongiaLL, sortOrderby);
    }//GEN-LAST:event_btSearch1ActionPerformed

    private void btSearch1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btSearch1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btSearch1ItemStateChanged

    private void btSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearch2ActionPerformed
        // TODO add your handling code here:
        SachCtrl sachCtrl = new SachCtrl();
        String mads, tenS, tacGia, nhaXB, namXB, sortOrderby;
        float dongiaNN, dongiaLL;
        mads = getStr(tfMaDS2);
        tenS = getStr(tfTenS2);
        tacGia = getStr(tfTacGia2);
        nhaXB = getStr(tfNhaXB2);
        namXB = getStr(tfNamXB2);
        sortOrderby = getStr(cmbSapXep2);
        dongiaNN = Float.parseFloat(tfGiaNN2.getText().trim());
        dongiaLL = Float.parseFloat(tfGiaLN2.getText().trim());
        sachCtrl.SachtoTable(tbResultSach2, mads, tenS, tacGia, nhaXB, namXB, dongiaNN, dongiaLL, sortOrderby);
    }//GEN-LAST:event_btSearch2ActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        int selectedIndex = this.jTabbedPane1.getSelectedIndex();
        SachCtrl sachCtrl = new SachCtrl();
        String mads, tenS, tacGia, nhaXB, namXB, sortOrderby;
        float dongiaNN, dongiaLL;
        switch (selectedIndex) {
            case 1://tab muon tra
                mads = getStr(tfMaDS1);
                tenS = getStr(tftenS1);
                tacGia = getStr(tftacGia1);
                nhaXB = getStr(tfnhaXB1);
                namXB = getStr(tfnamXB1);
                sortOrderby = getStr(cmbSapXep1);
                dongiaNN = Float.parseFloat(tfGiaNN1.getText().trim());
                dongiaLL = Float.parseFloat(tfGiaLN1.getText().trim());
                sachCtrl.SachtoTable(tbResultTb1, mads, tenS, tacGia, nhaXB, namXB, dongiaNN, dongiaLL, sortOrderby);
                break;
            case 2://tab quan li sach
                mads = getStr(tfMaDS2);
                tenS = getStr(tfTenS2);
                tacGia = getStr(tfTacGia2);
                nhaXB = getStr(tfNhaXB2);
                namXB = getStr(tfNamXB2);
                sortOrderby = getStr(cmbSapXep2);
                dongiaNN = Float.parseFloat(tfGiaNN2.getText().trim());
                dongiaLL = Float.parseFloat(tfGiaLN2.getText().trim());
                sachCtrl.SachtoTable(tbResultSach2, mads, tenS, tacGia, nhaXB, namXB, dongiaNN, dongiaLL, sortOrderby);
                break;
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void tbResultTb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbResultTb1MouseClicked
        // TODO add your handling code here:
        this.RoSachDialog.setAlwaysOnTop(true);
        this.RoSachDialog.setLocationRelativeTo(this.panelltimkiem1);
        this.RoSachDialog.pack();
        this.RoSachDialog.setVisible(true);


    }//GEN-LAST:event_tbResultTb1MouseClicked

    private void RSDSpinSoLuongSachStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RSDSpinSoLuongSachStateChanged
        // TODO add your handling code here:

        setTongTien();
    }//GEN-LAST:event_RSDSpinSoLuongSachStateChanged

    private void RSDspinSoNgayMuonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RSDspinSoNgayMuonStateChanged
        // TODO add your handling code here:

        setTongTien();
    }//GEN-LAST:event_RSDspinSoNgayMuonStateChanged

    private void RSDLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RSDLuuActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) this.tbRoSach.getModel();
        Object[] item = new Object[5];
        int row = this.tbResultTb1.getSelectedRow();
        item[0] = tbResultTb1.getValueAt(row, 0);
        item[1] = tbResultTb1.getValueAt(row, 1);
        item[2] = tbResultTb1.getValueAt(row, 5);
        item[3] = this.RSDSpinSoLuongSach.getValue();
        item[4] = this.RSDspinSoNgayMuon.getValue();
        model.addRow(item);
        this.RoSachDialog.dispose();
    }//GEN-LAST:event_RSDLuuActionPerformed

    private void RoSachDialogWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_RoSachDialogWindowOpened
        // TODO add your handling code here:
        int row = this.tbResultTb1.getSelectedRow();
        this.RSDMaSach.setText(tbResultTb1.getValueAt(row, 0).toString());
        this.RSDTenSach.setText(tbResultTb1.getValueAt(row, 1).toString());
        this.RSDDongia.setText(tbResultTb1.getValueAt(row, 5).toString());
        setTongTien();
    }//GEN-LAST:event_RoSachDialogWindowOpened

    private void btDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelete1ActionPerformed
        // TODO add your handling code here:
        int row = this.tbRoSach.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(panelRoSach, "Chọn 1 hàng để xóa!");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tbRoSach.getModel();
        model.removeRow(row);
    }//GEN-LAST:event_btDelete1ActionPerformed

    private void tfSoDTDocGiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfSoDTDocGiaFocusLost
        // TODO add your handling code here:
        DocGiaCtrl dgctr = new DocGiaCtrl();
        try {
            dgctr.loadCmb(this.tfSoDTDocGia, this.cmbLoadSoDTDocGia);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this.panelDocGia, ex);
        }
    }//GEN-LAST:event_tfSoDTDocGiaFocusLost

    private void cmbLoadSoDTDocGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbLoadSoDTDocGiaMouseClicked
        // TODO add your handling code here:
        DocGiaCtrl dgctr = new DocGiaCtrl();
        DocGia dg = dgctr.loadDocGia(this.cmbLoadSoDTDocGia);
        tfSoDTDocGia.setText(dg.getSoDT());
        tfTenDocGia.setText(dg.getTenDG());
        tfLopDocGia.setText(dg.getLop());
        tfKhoaDocGia.setText(dg.getKhoa());
    }//GEN-LAST:event_cmbLoadSoDTDocGiaMouseClicked

    private void btXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXacNhanActionPerformed
        // TODO add your handling code here:
        int rowCount = this.tbRoSach.getRowCount();
        if (rowCount == 0) {
            JOptionPane.showMessageDialog(this.panelRoSach, "Ro sach dang trong!");
            return;
        }
        DocGiaCtrl dgctr = new DocGiaCtrl();
        String maDG;
        try {
            maDG = dgctr.themDG(tfSoDTDocGia, tfTenDocGia, tfLopDocGia, tfKhoaDocGia);//luon tra ve madg
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this.panelDocGia, ex);
            return;
        }
        for (int i = 1 ; i <= rowCount;i++){
            MuonSach(nv.getMaNV(),maDG,tbRoSach.getValueAt(i,0).toString(),tbRoSach.getValueAt(i,3).toString(),tbRoSach.getValueAt(i,4).toString());
        }
    }//GEN-LAST:event_btXacNhanActionPerformed

    private String getStr(JTextField tf) {
        String rs = tf.getText().trim();
        if (rs.equals("")) {
            return null;
        } else {
            return rs;
        }
    }

    private String getStr(JComboBox cmb) {
        String rs = cmb.getSelectedItem().toString();
        if (rs.equals("")) {
            return null;
        } else {
            return rs;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPannelQuanLiSach;
    private javax.swing.JTextField RSDDongia;
    private javax.swing.JButton RSDLuu;
    private javax.swing.JTextField RSDMaSach;
    private javax.swing.JSpinner RSDSpinSoLuongSach;
    private javax.swing.JTextField RSDTenSach;
    private javax.swing.JLabel RSDTongTien;
    private javax.swing.JSpinner RSDspinSoNgayMuon;
    private javax.swing.JDialog RoSachDialog;
    private javax.swing.JTable TbTopKH;
    private javax.swing.JButton btAdd2;
    private javax.swing.JButton btDelete1;
    private javax.swing.JButton btLogout;
    private javax.swing.JButton btSave;
    private javax.swing.JButton btSearch1;
    private javax.swing.JButton btSearch2;
    private javax.swing.JButton btXacNhan;
    private javax.swing.JButton btdelete2;
    private javax.swing.JButton btfix2;
    private javax.swing.JComboBox<String> cmbChucNang;
    private javax.swing.JComboBox<String> cmbLoadSoDTDocGia;
    private javax.swing.JComboBox<String> cmbSapXep1;
    private javax.swing.JComboBox<String> cmbSapXep2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpannelMuonTra;
    private javax.swing.JLabel lbSachDaChoMuon;
    private javax.swing.JLabel lbTenNV;
    private javax.swing.JLabel lbVaiTro;
    private javax.swing.JPanel panelChaoMung;
    private javax.swing.JPanel panelDocGia;
    private javax.swing.JPanel panelNV;
    private javax.swing.JPanel panelRoSach;
    private javax.swing.JPanel panelltimkiem1;
    private javax.swing.JPasswordField pfpass;
    private javax.swing.JTable tbResultSach2;
    private javax.swing.JTable tbResultTb1;
    private javax.swing.JTable tbRoSach;
    private javax.swing.JTable tbTopNV;
    private javax.swing.JTable tbTopSach;
    private javax.swing.JTextField tfGiaLN1;
    private javax.swing.JTextField tfGiaLN2;
    private javax.swing.JTextField tfGiaNN1;
    private javax.swing.JTextField tfGiaNN2;
    private javax.swing.JTextField tfKhoaDocGia;
    private javax.swing.JTextField tfLopDocGia;
    private javax.swing.JTextField tfMaDS1;
    private javax.swing.JTextField tfMaDS2;
    private javax.swing.JTextField tfNamXB2;
    private javax.swing.JTextField tfNhaXB2;
    private javax.swing.JTextField tfSoDTDocGia;
    private javax.swing.JTextField tfTacGia2;
    private javax.swing.JTextField tfTenDocGia;
    private javax.swing.JTextField tfTenS2;
    private javax.swing.JTextField tfnamXB1;
    private javax.swing.JTextField tfnhaXB1;
    private javax.swing.JTextField tftacGia1;
    private javax.swing.JTextField tftenS1;
    // End of variables declaration//GEN-END:variables

    private void loadPanelNV() {
        this.lbTenNV.setText(nv.getTenNV());
        this.lbVaiTro.setText(nv.getVaiTro());
        try {
            this.lbSachDaChoMuon.setText(nv.SoLuotChoMuon());
        } catch (SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setTongTien() {
        float dongia = Float.parseFloat(this.RSDDongia.getText().trim());
        Double sum;
        Double soLuongSach = Double.parseDouble(this.RSDSpinSoLuongSach.getValue().toString());
        Double soNgayMuon = Double.parseDouble(this.RSDspinSoNgayMuon.getValue().toString());
        sum = dongia * soLuongSach + soNgayMuon * 1000;
        this.RSDTongTien.setText(Double.toString(sum));

    }

    private void MuonSach(String maNV, String maDG, String MaDS, String soLuongSach, String soNgayMuon) {
        MuonTraCtrl mtCtr = new MuonTraCtrl();
        mtCtr.setMaDG(maDG);
        mtCtr.setMaDS(MaDS);
        mtCtr.setMaNV(maNV);
        mtCtr.setSoLuongSach(Integer.valueOf(soLuongSach));
        mtCtr.setSoNgayMuon(Integer.valueOf(soNgayMuon));
        try {
            mtCtr.muonSach();
        } catch (SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null,"loi o ma dau sach :"+MaDS + ex);
        }

    }
}
