/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.panelNVCtr;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.NhanVien;

/**
 *
 * @author coc
 */
public class MainForm extends javax.swing.JFrame {

    private NhanVien nv;

    /**
     * Creates new form MainForm
     */

    public void setNv(NhanVien nv) {
        this.nv = nv;
    }

    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelChaoMung = new javax.swing.JPanel();
        panelNV = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbTenNV = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbVaiTro = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbSachDaChoMuon = new javax.swing.JLabel();
        cmbChucNang = new javax.swing.JComboBox<>();
        btSave = new javax.swing.JButton();
        pfpass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelChaoMung.setBackground(new java.awt.Color(255, 255, 255));

        panelNV.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setText("Hi,");

        lbTenNV.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lbTenNV.setText("TenNV");
        lbTenNV.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel2.setText("Vai trò:");

        lbVaiTro.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        lbVaiTro.setText("chucvu");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel3.setText("Số sách đã cho mượn:");

        lbSachDaChoMuon.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        lbSachDaChoMuon.setText("jLabel4");

        cmbChucNang.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        cmbChucNang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cài đặt", "Đổi tên", "Đổi Mật Khẩu" }));
        cmbChucNang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbChucNangActionPerformed(evt);
            }
        });

        btSave.setBackground(new java.awt.Color(0, 102, 102));
        btSave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btSave.setForeground(new java.awt.Color(255, 255, 255));
        btSave.setText("Save");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNVLayout = new javax.swing.GroupLayout(panelNV);
        panelNV.setLayout(panelNVLayout);
        panelNVLayout.setHorizontalGroup(
            panelNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNVLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTenNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelNVLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lbVaiTro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pfpass)
                    .addGroup(panelNVLayout.createSequentialGroup()
                        .addGroup(panelNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelNVLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(lbSachDaChoMuon))
                            .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelNVLayout.setVerticalGroup(
            panelNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbTenNV))
                .addGap(18, 18, 18)
                .addGroup(panelNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbVaiTro))
                .addGap(18, 18, 18)
                .addGroup(panelNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbSachDaChoMuon))
                .addGap(18, 18, 18)
                .addComponent(cmbChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pfpass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelChaoMungLayout = new javax.swing.GroupLayout(panelChaoMung);
        panelChaoMung.setLayout(panelChaoMungLayout);
        panelChaoMungLayout.setHorizontalGroup(
            panelChaoMungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelChaoMungLayout.createSequentialGroup()
                .addContainerGap(812, Short.MAX_VALUE)
                .addComponent(panelNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelChaoMungLayout.setVerticalGroup(
            panelChaoMungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChaoMungLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Chào mừng", null, panelChaoMung, "");
        panelChaoMung.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        // TODO add your handling code here:
        char[] c = this.pfpass.getPassword();

        try {
            this.nv = panelNVCtr.save(cmbChucNang, nv, new String(c));
            loadPanelNV();
            panelNVCtr.show(pfpass, btSave, false);
            this.cmbChucNang.setSelectedIndex(0);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(panelChaoMung, ex);
        }

    }//GEN-LAST:event_btSaveActionPerformed

    private void cmbChucNangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbChucNangActionPerformed
        // TODO add your handling code here:
        panelNVCtr.CaiDat(cmbChucNang, pfpass, btSave);
    }//GEN-LAST:event_cmbChucNangActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

        //load panel NhanVien
        loadPanelNV();
        panelNVCtr.show(pfpass, btSave, false);
        this.cmbChucNang.setSelectedIndex(0);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSave;
    private javax.swing.JComboBox<String> cmbChucNang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbSachDaChoMuon;
    private javax.swing.JLabel lbTenNV;
    private javax.swing.JLabel lbVaiTro;
    private javax.swing.JPanel panelChaoMung;
    private javax.swing.JPanel panelNV;
    private javax.swing.JPasswordField pfpass;
    // End of variables declaration//GEN-END:variables

    private void loadPanelNV() {
        this.lbTenNV.setText(nv.getTenNV());
        this.lbVaiTro.setText(nv.getVaiTro());
        try {
            this.lbSachDaChoMuon.setText(nv.SoLuotChoMuon());
        } catch (SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
